---
title: "Wanting ‘the whole loaf’: Zero-sum thinking about love is associated with prejudice against consensual non-monogamists"
date: 2017-01-01
author:
  - name: Tyler Burleigh
  - name: Alicia Rubel
  - name: Daniel Meegan
categories: 
  - Sexuality
  - Prejudice
  - 'Consensual Non-Monogamy'
  - 'Zero-sum Thinking'
  - Experimental
pub-info:
  reference: >-
    Burleigh, T. J., Rubel, A. N., & Meegan, D. V. (2017). Wanting ‘the whole loaf’: Zero-sum thinking about love is associated with prejudice against consensual non-monogamists. Psychology & Sexuality, 8(1-2), 24-40. doi: <a href="https://doi.org/10.1080/19419899.2016.1269020"><code>10.1080/19419899.2016.1269020</code></a>
  links:
    - name: 'Preprint'
      url: 'Burleigh, Rubel & Meegan - 2017 - Zero-sum thinking & anti-CNM prejudice.pdf'
      icon: fa-solid fa-file-pdf
      local: true
    - name: Final version
      url: https://doi.org/10.1080/19419899.2016.1269020
      icon: fa-solid fa-scroll
doi: 10.1080/19419899.2016.1269020
---

## Abstract

Consensual non-monogamy (CNM) is a relationship in which individuals agree that romantic or sexual relationships with others are permissible or desirable (e.g. polyamory or open relationships). Although anti-CNM prejudice is prevalent, it is not well understood. We propose that one of the bases of anti-CNM prejudice is zero-sum thinking about love – the perception that one person’s love gained is another’s love lost. We outline our theory and then present three studies that test our predictions. In these studies, participants read a vignette that depicted characters who were in a CNM or monogamous relationship, and then judged aspects of the characters and their relationship. In Study 1, participants who read the CNM vignette judged the protagonist’s love for their initial romantic partner before and after they became involved with a second partner. Zero-sum thinking was operationally defined as the within-subject change in love ratings. In Studies 2 and 3, participants rated their agreement with items from a new preliminary measure of zero-sum romantic beliefs. We measured CNM devaluation by asking for ratings of the relationships and of individuals in the relationships. Supporting our predictions, in all three studies we found that zero-sum thinking about love was associated with increased CNM devaluation. We end by briefly discussing the implications of our findings.


## Important figure

![Figure 2. This figure shows that increased zero-sum romantic beliefs were associated with greater devaluation of CNM (steeper slopes) in Study 2. It represents a simple slopes analysis of relationship vignette (monogamous, CNM) predicting evaluative judgment scores at 1 SD above the mean of zero-sum romantic beliefs, at the mean of zero-sum romantic beliefs, and 1 SD below the mean of zero-sum romantic beliefs.](fig2.jpg)
