---
title: Hello blogdown
author: ~
date: '2018-11-12'
slug: hello-blogdown
categories: [blog]
tags: [meta]
description: Hello blogdown
---

I like to reinvent my website from time to time. This means doing a "spring cleaning," but also using the opportunity to try something new. I like to experiment with new designs, layouts, and software. I've been using [R]("https://www.r-project.org") quite a lot lately, and for the sake of curiosity I'm trying to see how many different uses I can find for it. This time I decided to try using [blogdown]("https://bookdown.org/yihui/blogdown") to run my site.

# Why blogdown?

I've decided to use blogdown for a few reasons.

## 1

As [James Somers](https://twitter.com/jsomers) put it in an article over at The Atlantic, [The Scientific Paper is Obsolete](https://www.theatlantic.com/science/archive/2018/04/the-scientific-paper-is-obsolete/556676). I'm interested in new ways of doing scientific publishing, not just for some of the reasons cited in that article -- e.g., the stodgy printed-on-papoer article can't accommodate new and useful ways of presenting knowledge like interactive computational notebooks can -- but also because I've found myself transitioning out of academia and into industry where the scientific process takes a different form.

In academia, knowledge is created and careers are built upon the publication of journal articles -- end results that can often take years to achieve given the glacial pace of peer-review. But in industry science is more agile, taking shape in blips and bursts as it is needed to inform different decisions. The end result is better decisions, but much of the process that lead to those decisions can be lost unless someone is making an effort to document it. 

Part of my industry transition has also involved placing a greater emphasis on "data science" where the process is *almost as much* about applying programming and other technical skills as it is about applying theory and testing hypotheses. I usually learn new technical skills by jumping right in and trying to solve problems, but I also find that writing helps to develop explicit knowledge of what it is that I've learned to do in practice. It also becomes a resource for future-me to look back at so I don't re-tread the same ground!
 
