---
title: White papers
author: ~
date: '2044-12-31'
slug: white-papers
categories: []
tags: []
description: My white-papers
---

- Winter, N., Burleigh, T., Kennedy, R. & Clifford, S. (2019). A Simplified Protocol to Screen Out VPS and International Respondents Using Qualtrics. [[PDF]](https://tylerburleigh.com/pubs/Winter, Burleigh, Kennedy, Clifford - 2019 - A Simplified Protocol to Screen Out VPS and International Respondents Using Qualtrics.pdf)

- Burleigh, T., Kennedy, R. & Clifford, S. (2018). How to Screen Out VPS and International Respondents Using Qualtrics: A Protocol. [[PDF]](https://tylerburleigh.com/pubs/Burleigh et al - 2018 - How to Screen out VPS and International Respondents using Qualtrics.pdf)

- Burleigh, T. J. & Glimcher, P. G. (2017). Building the next generation of early warning systems in education. [[PDF]](https://tylerburleigh.com/pubs/Burleigh & Glimcher - 2017 - Next-Gen Early Warning Systems.pdf)

- Burleigh, T. J. & Glimcher, P. G. (2017). Finding the best fit: Building a novel student-school compatibility tool to improve school choice. [[PDF]](https://tylerburleigh.com/pubs/Burleigh & Glimcher - 2017 - Finding the Best Fit.pdf)