---
date: ""
disableComments: true
slug: ""
title: Teaching
output: html_document
---

I like to skill-share and I've given some talks and lectures for my peers in various contexts. I was also an Adjunct Professor for the <a href="https://sps.columbia.edu/academics/masters/applied-analytics">Applied Analytics Master's program at Columbia University</a> for the Fall 2018 semester (that was fun :).

# Psychology

<span class="date" style="font-family:'Lucida Console', Monaco, monospace">2019/04</span> - <a href="https://docs.google.com/presentation/d/1yJlEKKJ31q5y8EwctQ4YtetD2ckEiDoFqdHaL-J8KxM">A whirlwind tour of persuasion psychology</a>

<span style="margin-left:30px;display:block;margin-top:-10px">An educational talk for a non-academic audience about the foundations of persuasion psychology. Covers human evolution, irrationality, heuristics and biases, cognitive dissonance, and social norms.</span>

<span class="date" style="font-family:'Lucida Console', Monaco, monospace">2017/11</span> - <a href="https://docs.google.com/presentation/d/1McU7gic4EqYL7RlpDOKZkNpwmH9eoevbj6G_XqcGhAQ">What and how we measure things in psychology</a>

<span style="margin-left:30px;display:block;margin-top:-10px">An educational talk for a non-academic audience about measurements in psychology. Sort of a 101 on measurement: What a measurement is, how a measurement comes to be created, and why we measure things at all. Followed by a deper dive into the measurement of emotions.</span>


# Algorithms

<span class="date" style="font-family:'Lucida Console', Monaco, monospace">2017/07</span> - <a href="https://docs.google.com/presentation/d/1irgMB7cx5HfUYvMStFtKcF00Zhamv7MIfoL5LY-gRaw">Predicting and preventing depression episodes</a>

<span style="margin-left:30px;display:block;margin-top:-10px">An educational / motivational talk for a non-academic audience. The subject was depression and predicting depression using data and algorithms. The talk was at the introductory level and was meant to get people excited about the potential of predictive algorithms.</span>

