---
date: ""
disableComments: true
slug: ""
title: Writing
output: html_document
---

```{r include = FALSE}
id <- 'Y6l9qBUAAAAJ'
sch <- scholar::get_profile(id)
```

I've authored peer-reviewed scholarly articles and white papers.

As of `r Sys.Date()`, my papers were cited `r sch$total_cites` times and my [h-index](https://en.wikipedia.org/wiki/H-index) was `r sch$h_index`. (source: [Google Scholar](https://scholar.google.com/citations?user=Y6l9qBUAAAAJ))

# Papers

## Uncanny Valley

- Burleigh, T. J. (2015). A challenge to the study of individual differences in uncanny valley sensitivity: The importance of looking at individual-level response patterns. Interaction Studies, 16(2). [[PDF]](https://tylerburleigh.com/pubs/Burleigh et al - 2015 - A challenge to the study of individual differences in uncanny valley sensitivity.pdf) 

- Ferrey, A., Burleigh, T. J., & Fenske, M. (2015). Stimulus-category competition, inhibition and affective devaluation: A novel account of the Uncanny Valley. Frontiers in Psychology, 6:249. doi: 10.3389/fpsyg.2015.00249. [[PDF]](https://tylerburleigh.com/pubs/Ferrey, Burleigh and Fenske - 2015 - Stimulus-category competition.pdf) 

- Burleigh, T. J. & Schoenherr, J. R. (2015) A reappraisal of the uncanny valley: Categorical perception or frequency-based sensitization? Frontiers in Psychology, 5:1488. doi: 10.3389/fpsyg.2014.01488. [[PDF]](https://tylerburleigh.com/pubs/Burleigh and Schoenherr - 2015 - A reappraisal of the uncanny valley.pdf) 

- Schoenherr, J. R. & Burleigh, T. J. (2015) Uncanny sociocultural categories. Frontiers in Psychology, 5:1456. doi: 10.3389/fpsyg.2014.01456. [[PDF]](https://tylerburleigh.com/pubs/Schoenherr and Burleigh - 2015 - Uncanny sociocultural categories.pdf) 

- Burleigh, T. J., Schoenherr, J. R., & Lacroix, G. L. (2013). Does the uncanny valley exist? An empirical test of the relationship between eeriness and the human likeness of digitally created faces. Computers in Human Behavior, 29(3), 759-771. doi: 10.1016/j.chb.2012.11.021. [[PDF]](https://tylerburleigh.com/pubs/Burleigh, Schoenherr and Lacroix - 2013 - Does the uncanny valley exist.pdf) 

## Social Cognition

- Burleigh, T. J., Rubel, A. N. & Meegan, D. V. (2017). Wanting 'the whole loaf': Zero-sum thinking about love is associated with prejudice against consensual nonmonogamists. Psychology & Sexuality. doi: 10.1080/19419899.2016.1269020. [[PDF]](https://tylerburleigh.com/pubs/Burleigh, Rubel & Meegan - 2017 - Zero-sum thinking & anti-CNM prejudice.pdf) 

- Burleigh, T. J. & Meegan, D. V. (2017). Risky prospects and risk aversion tendencies: Competition in the classroom depends on grading practices and knowledge of peer-status. Social Psychology of Education, 1-13. doi: 10.1007/s11218-017-9414-x. [[PDF]](https://tylerburleigh.com/pubs/Burleigh & Meegan - 2017 - Risky prospects, competition in the classroom.pdf)  

- Burleigh, T. J., & Meegan, D. V. (2013). Keeping up with the Joneses affects perceptions of distributive justice. Social Justice Research, 26(2), 120-131. doi: 10.1007/s11211-013-0181-3. [[PDF]](https://tylerburleigh.com/pubs/Burleigh and Meegan - 2013 - Keeping up with the Joneses.pdf) 


## Sexuality

- Rubel, A. N. & Burleigh, T. J. (in press). Counting polyamorists who count: Prevalence and definitions of an under-researched form of consensual nonmonogamy. Sexualities. [[PDF]](https://tylerburleigh.com/pubs/Rubel & Burleigh - 2018 - Counting polyamorists who count.pdf)

- Wood, J., Desmarais, S., Burleigh, T., & Milhausen, R. R. (2018). Reasons for sex and relational outcomes in consensually nonmonogamous and monogamous relationships: A self-determination theory approach. Journal of Social and Personal Relationships, 35(4), 632-654. doi: 10.1177/0265407517743082. [[PDF]](https://tylerburleigh.com/pubs/Wood et al - 2018 - Reasons for sex in CNM and monogamous relationships.pdf) 

## Decision-Making

- Sparks, A., Burleigh, T., & Barclay, P. (2015). We can see inside: Accurate prediction of Prisoner's Dilemma decisions in announced games following a face-to-face interaction. Evolution and Human Behavior. doi: 10.1016/j.evolhumbehav.2015.11.003. [[PDF]](http://www.ehbonline.org/article/S1090-5138%2815%2900119-1/pdf) 


# White Papers

- Winter, N., Burleigh, T., Kennedy, R. & Clifford, S. (February 1, 2019). A Simplified Protocol to Screen Out VPS and International Respondents Using Qualtrics. Available at SSRN:
https://ssrn.com/abstract=3327274 [[PDF]](https://tylerburleigh.com/pubs/Winter, Burleigh, Kennedy, Clifford - 2019 - A Simplified Protocol to Screen Out VPS and International Respondents Using Qualtrics.pdf)

- Burleigh, T., Kennedy, R. & Clifford, S. (October 12, 2018). How to Screen Out VPS and International Respondents Using Qualtrics: A Protocol. Available at SSRN: https://ssrn.com/abstract=3265459 [[PDF]](https://tylerburleigh.com/pubs/Burleigh et al - 2018 - How to Screen out VPS and International Respondents using Qualtrics.pdf)

- Burleigh, T. J. & Glimcher, P. G. (2017). Building the next generation of early warning systems in education. [[PDF]](https://tylerburleigh.com/pubs/Burleigh & Glimcher - 2017 - Next-Gen Early Warning Systems.pdf)

- Burleigh, T. J. & Glimcher, P. G. (2017). Finding the best fit: Building a novel student-school compatibility tool to improve school choice. [[PDF]](https://tylerburleigh.com/pubs/Burleigh & Glimcher - 2017 - Finding the Best Fit.pdf)

